server:
  port: 8080   # 默认端口，可自行修改

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      # password: yourredispassword   # 如果你的 Redis 设置了密码，取消注释并填写

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 开启 SQL 日志
  global-config:
    db-config:
      id-type: auto   # 主键自增策略